# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1024648f988bbb0112e1d0c2a8f60b9d2274346056005ca263ffc6a2c9bcdb551666aa93a13bcde6020922b20ded15fbb6984572d25d251d19f2b98bc58a8c27

test:
  secret_key_base: b1833152d1fb17345f4ecd9e04ec045a9920d96282cd8d73df94249ed9ccea2b667e41b8324377cc46833a929bb2fddca6d111f52d8059f32fa94088d7851223

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
